using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Commander.SourceGenerator;

/// <summary>
/// Emits a per-assembly extension method <c>AddCommanderHandlers</c> that registers every
/// command handler, query handler, stream query handler, event handler and command validator
/// using only <c>Microsoft.Extensions.DependencyInjection</c> APIs — no runtime reflection,
/// fully trim/AOT safe.
/// </summary>
[Generator]
public sealed class CommanderRegistrationGenerator : IIncrementalGenerator
{
    private const string CommanderNamespace = "Commander";

    private static readonly string[] HandlerInterfaceNames =
    [
        "ICommandHandler",
        "IQueryHandler",
        "IStreamQueryHandler",
        "IEventHandler",
        "ICommandValidator",
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerCandidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax cls && cls.BaseList is not null,
                transform: static (ctx, _) => GetHandlerRegistration(ctx))
            .Where(static x => x is not null)
            .Select(static (x, _) => x!.Value);

        var assemblyName = context.CompilationProvider
            .Select(static (compilation, _) => compilation.AssemblyName ?? "Default");

        var combined = handlerCandidates.Collect().Combine(assemblyName);

        context.RegisterSourceOutput(combined, static (spc, source) =>
        {
            var (handlers, asmName) = source;
            if (handlers.IsDefaultOrEmpty)
            {
                return;
            }

            var hintName = $"CommanderRegistrations.g.cs";
            var sourceText = SourceText.From(BuildSource(handlers, asmName), Encoding.UTF8);
            spc.AddSource(hintName, sourceText);
        });
    }

    private static HandlerRegistration? GetHandlerRegistration(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classNode)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(classNode) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        if (classSymbol.IsAbstract || classSymbol.IsGenericType || classSymbol.DeclaredAccessibility != Accessibility.Public)
        {
            return null;
        }

        var serviceTypes = ImmutableArray.CreateBuilder<string>();
        foreach (var iface in classSymbol.AllInterfaces)
        {
            if (!iface.IsGenericType)
            {
                continue;
            }

            if (iface.ContainingNamespace?.ToDisplayString() != CommanderNamespace)
            {
                continue;
            }

            var name = iface.Name;
            if (System.Array.IndexOf(HandlerInterfaceNames, name) < 0)
            {
                continue;
            }

            serviceTypes.Add(iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }

        if (serviceTypes.Count == 0)
        {
            return null;
        }

        return new HandlerRegistration(
            classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            serviceTypes.ToImmutable());
    }

    private static string BuildSource(ImmutableArray<HandlerRegistration> handlers, string assemblyName)
    {
        var safeAsmName = SanitizeIdentifier(assemblyName);
        var distinct = handlers
            .SelectMany(h => h.ServiceTypes.Select(s => (Service: s, Implementation: h.ImplementationType)))
            .Distinct()
            .OrderBy(t => t.Service, System.StringComparer.Ordinal)
            .ThenBy(t => t.Implementation, System.StringComparer.Ordinal)
            .ToArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Commander.SourceGenerator. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("namespace Commander");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Generated extension method that registers every Commander handler, validator and stream query handler");
        sb.AppendLine("    /// found in this compilation. Reflection-free; AOT and trim safe.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class CommanderGeneratedRegistrations_{safeAsmName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        /// <summary>Register every Commander handler discovered in <c>{assemblyName}</c>.</summary>");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddCommanderHandlers(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        sb.AppendLine("            global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped)");
        sb.AppendLine("        {");

        if (distinct.Length == 0)
        {
            sb.AppendLine("            // No Commander handlers were discovered in this compilation.");
        }
        else
        {
            foreach (var (service, implementation) in distinct)
            {
                sb.AppendLine(
                    $"            services.TryAddEnumerable(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof({service}), typeof({implementation}), lifetime));");
            }
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string SanitizeIdentifier(string assemblyName)
    {
        var sb = new StringBuilder(assemblyName.Length);
        foreach (var c in assemblyName)
        {
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }
        if (sb.Length > 0 && char.IsDigit(sb[0]))
        {
            sb.Insert(0, '_');
        }
        return sb.ToString();
    }

    private readonly record struct HandlerRegistration(string ImplementationType, ImmutableArray<string> ServiceTypes);
}
